#配置mysql
spring:
  datasource:
    url: jdbc:mysql://140.143.165.150:3306/neptune?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8&useSSL=false&allowMultiQueries=true
    username: neptune
    password: chenhu82028
    driverClassName: com.mysql.cj.jdbc.Driver
    #Druid连接池配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties.druid.stat.mergeSql: true;
    connectionProperties.druid.stat.slowSqlMillis: 5000
#Mybatis
mybatis:
  #加载mybatis主要配置类
  config-location: classpath:mybatis/mybatis-config.xml
  #加载mapper配置类
  mapper-locations: classpath:mapper/*.xml
  #加载mapper实体类
  type-aliases-package: com.lathingfisher.neptune.pojo
